# Site settings
title: "al-Raqmiyyāt: Digital Islamic History"
header-img: images/covers/althurayya.jpg
email: romanov.maxim@gmail.com
description:
  "Reading Traditional Sources with Nontraditional Methods"
baseurl: ""
url: "http://maximromanov.github.io"
share:  true
twitter_username: maximromanov
github_username:  maximromanov
facebook_username:  maxim.romanov.925
disqus_shortname: alraqmiyyat

# Build settings
markdown:    redcarpet
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]


# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname


# Markdown Processors
maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

rdiscount:
  extensions: []

redcarpet:
  extensions: ["footnotes", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "with_toc_data"]

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style